"""Added FeedbackRecord table

Revision ID: 451f93791180
Revises: c0c0234d57fe
Create Date: 2026-08-02 18:54:11.076683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451f93791180'
down_revision = 'c0c0234d57fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
