"""Added role and google_id columns to User

Revision ID: c0c0234d57fe
Revises: 
Create Date: 2026-08-02 10:27:53.609468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c0234d57fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        # FIXED: Replaced None with 'uq_user_google_id'
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # FIXED: Replaced None with 'uq_user_google_id'
        batch_op.drop_constraint('uq_user_google_id', type_='unique')
        batch_op.drop_column('google_id')
        batch_op.drop_column('role')

    # ### end Alembic commands ###